### ISSUE TITLE
Creating CI CD pipeline

### ISSUE THREAD

**Issue by parth-sinha18** [Web-Development-Organisation/time-securiy#4]
Creating CI CD pipeline and configure them. The pipeline should be created to connect github and AWS.

**Comment by parth-sinha18** [comment]
CI CD pipeline has been created and just need to work on Dockerfile to so it should launch postgresql container in AWS and on local machine and we can access it.

**Comment by sinhaparth5** [comment]
Yellow??

**Comment by sinhaparth5** [comment]
CI CD pipeline has been created using Jenkins, Ansible and Github

**Comment by sinhaparth5** [comment]
May require changes as to move to more secure pipeline, keeping ticket open.

**Comment by sinhaparth5** [comment]
Pipeline created
